use_cache: False
debug: True

params:
  lr: 0.01
  clipnorm: 0.001
  ngram_range: 1 # 2 for bi-grams (takes a lot longer to train)
  batch_size: 1024
  max_features: 200000
  maxlen: 100 # max length of document
  embedding_dims: 50 # dimensions of embedding
  epochs: 10

